const AppStrings = {
  appName: 'UHS',
  norecordFound: 'No record found',
  howCanIhelp: 'How can I help you today?',
  login: 'SIGN IN',
  signOut: 'Sign Out',
  welcome: 'WELCOME TO MEMBER PORTAL',
  enter_mobile_number: 'Enter Mobile Number',
  cancel: 'CLOSE',
  ok: 'OK',
  YES: 'YES',
  SKIP: 'SKIP',
  send: 'Send',
  loginTo: 'Login To CarynHealth',
  enter_your_email: 'ENTER YOUR EMAIL',
  chnage_password: 'RESET MY PASSWORD',
  enter_name: 'ENTER YOUR EMAIL',
  enter_password: 'ENTER PASSWORD',
  enter_new_password: 'ENTER NEW PASSWORD',
  login_with_new_password: 'Login With New Password',
  required_password: 'Please enter required fields',
  server_error: 'Something Went Wrong',
  app_name: 'CarynHealth',
  notifications: 'Notifications',
  documents: 'Documents',
  channelId: '28012021',
  channelName: 'CarynHealth',
  channelDescription: 'CarynHealth',
  code: 'CODE',
  enterCode: 'ENTER CODE',
  confirmPassword: 'ENTER NEW PASSWORD AGAIN',
  changePassword: 'CHANGE PASSWORD',
  forgotText: 'Forgot your password?',
  lets_Check: "Let's check if your email has been registered on the portal",
  emailIsRegistered: 'if your email has been registered on the portal',
  havingtrouble: 'Having trouble in logging in?',
  bottomForgot: 'Enter your Email and we will send a message to reset your password',
  changeNewPassword: 'CHANGE NEW PASSWORD',
  allset: 'You are all set!',
  pleaseCheck: 'Please Check',
  enterValidEmail: 'Please enter valid email address',
  noInternet: 'There is no internet connection',
  enterValidPassword: 'Please enter valid password',
  remember_password: 'If you can’t remember your password, you can reset it by clicking the “Forgot your password?”',
  forgot_your_password: 'Forgot your password',
  exitApplication: 'Are you sure you want to Exit?',
  copyright: 'Copyright ©2020-2021 Universal Health Fellowship. All rights reserved. | Powered by CarynHealth',
  accesstoken:
    'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtYXJpY29wYSIsImV4cCI6MTYxMzM3OTIxNX0.umeGxjJeI5TWaFKciLoioQf5sF-ooXwh49126okPdp7ymovBbB3-QaZQw5iF5cn0Wljw9wQDIgRa0Cv4n9UZjQ',
  questionaryIncomplete: 'Hello! We notice that your health questionnaire is incomplete. Would you like to complete it now?',
  sessionExpired: 'Session Expired',
  sessionMessage: 'Your session has been expired.\nPlease try logging again!',
  needsFooter: '**For complete status, please refer to the Explanation of Sharing (EOS) mailed to your address on file',
  hq_notice: 'Hello! We notice that your health questionnaire is incomplete.\nWould you like to complete it now?',
  tryAgain: 'Something went wrong. Try again',

  //Card title name
  cardWallet: 'ID Cards',
  notices: 'Notices',
  programInformation: 'Program Information',
  myNeeds: 'My Needs',
  myTransactions: 'My Transactions',
  myNotifications: 'My Notifications',
  announcementsNotices: 'Announcements & Notices',
  findProvider: 'Find a Provider',
  healthQuestionnaire: 'Health Questionnaire',
  FAQs: 'FAQs',
  dashboard: 'Dashboard',
  telemed: 'Telemed',
  uhsCard: 'Membership Card',
  ContactInformation: 'Contact Information',
  paymentWallet: 'Payment Wallet',
  RequestPaymentCard: 'Request Payment Card',
  PaymentCard: 'Payment Card',
  ChnagePayment: 'Change Payment Method',

  //navigation screen names
  ProgramInformation: 'ProgramInformation',
  AppNavigator: 'AppNavigator',
  NotificationDetails: 'NotificationDetails',
  DocumentsNav: 'Documents',
  MyNeedsScreen: 'MyNeedsScreen',
  MyTransactionsNav: 'MyTransactions',
  HealthQuestionnaireNav: 'HealthQuestionnaire',
  DigitalHealthCardNew: 'DigitalHealthCardNew',
  HealthToolCard: 'HealthToolCard',
  HealthyShareCard: 'HealthyShareCard',
  ContactCardScreen: 'ContactCardScreen',
  paymentNav: 'PaymentWallet',
  RequestPaymentCardNav: 'RequestPaymentcard',
  PaymentCardNav: 'PaymentCard',
  ChnagePaymentMethod: 'ChnagePaymentMethod',

  //Card Type
  FindProvider_Type: 'FindProvider',
  Doc_Type: 'Documents',
  MyNeeds_Type: 'MyNeeds',
  MemberID_Type: 'MembershipId',
  HealthTool_Type: 'HealthTool',
  Notices_Type: 'Notices',
  PI_Type: 'ProgramInformation',
  Transaction_Type: 'MyTransaction',
  HQ_Type: 'HealthQuestionnaire',
  FAQ_Type: 'FAQs',
  C_Info_Type: 'ContactInformation',
  Payment_Type: 'Paymentwallet',
  RequestPaymentCard_type: 'RequestPaymentcard',
  contact_type: 'ContactInformation',
  announcementsNotices_type: 'AnnouncementsNotices',
  noticeUrl: 'https://www.universalhealthfellowship.org/notices/',

  //Chat Constants
  chnage_addOns: 'Change Add Ons',
  chnage_dependants: 'change Dependants',
  chatErrorTitle: 'Something went wrong',
  chatErrorMessage: `We're having some difficulties connecting to our knowledge base. Please try again after some time.`
}

export default AppStrings
